name: SuperClans
version: 1.0-SNAPSHOT
main: pl.noname.superclans.SuperClans
api-version: 1.16
depend:
  - Vault
  - PlaceholderAPI
commands:
  points:
    description: Zarządzanie punktami teamów
    aliases: punkty
    permission: superclans.points
  createclan:
    permission: superclans.createclan
    description: tworzy klan
    aliases: stworzklan
  pointshop:
    aliases: sklep
    description: otwiera sklep z punktami
  reloadShop:
    permission: superclans.reload
    description: Przeładowywuje config

